import type { Metadata } from "next";
import { Inter, Recursive } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import Providers  from "../components/Providers";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${recursive.className}`}>
        <Navbar />
        <main className="flex grainy-light flex-col flex-1">
          <div className="flex-1 flex flex-col">

            <Providers>
              {children}
            </Providers>
            
            </div>
          <Footer />
        </main>

        <Toaster />
      </body>
    </html>
  );
}
